iob_node_updater first try

diff --git a/iob_node_updater b/iob_node_updater
--- a/iob_node_updater
+++ b/iob_node_updater
@@ -1,15 +1,19 @@
 #!/bin/bash
 # iobroker node-update
 # written to help updating and fixing nodejs on linux (deb + rpm based Distros)
-VERSION="2023-09-05"
+VERSION="2023-09-08"
 echo -e "ioBroker node-update v$VERSION is starting. Please be patient!";
 NODE_MAJOR=18           #recommended major nodejs version for ioBroker, please adjust if the recommendation changes
 DOCKER=/opt/scripts/.docker_config/.thisisdocker
 HOST=$(hostname)
-NODERECOM=$(iobroker state getValue system.host."$HOST".versions.nodeNewestNext);  #recommended node version
-NODEINSTMAJOR=$(nodejs -v | cut -d.  -f1 | cut -c 2-3);
+NODERECOM=$(iobroker state getValue system.host."$HOST".versions.nodeNewestNext);  #reading node version from iob states
+if [[ $NODERECOM != "*.*.*" ]];
+then
+NODERECOMNF=1;
+fi;
+NODEINSTMAJOR=$(nodejs -v | cut -d. -f1 | cut -c 2-3);
 export LC_ALL=C;
-SYSTDDVIRT=$(systemd-detect-virt 2>/dev/null)
+SYSTDDVIRT=$(systemd-detect-virt 2>/dev/null);
 # ------------------------------
 # functions for ioBroker node-update
 # ------------------------------
@@ -73,9 +77,12 @@ SYSTDDVIRT=$(systemd-detect-virt 2>/dev/null)
 if [ -f "$DOCKER" ];
 then
         echo "Fixing Docker is not supported, please update your Docker Container";
-#       elif [ "$(id -u)" -eq 0 ];
-#                then
-#                        echo -e "This script must not be run as root! \nPlease use your standard user!"
+        unset LC_ALL;
+        exit 1;
+        elif [ "$(id -u)" -eq 0 ];
+                 then
+                         echo -e "This script must not be run as root! \nPlease use your standard user!"
+        unset LC_ALL;
         exit 1;
 fi;
 clear;
@@ -87,7 +94,7 @@ if [[ -n "$NODERECOM" ]];
         echo "Checking your installation now. Please be patient!"
         else
         NODERECOMNF=1;
-        echo -e "Could not detect recommended nodejs-version. Setting up the nodejs $NODE_MAJOR tree now.";
+        echo -e "No recommendation for nodejs version found on your system. We recommend to install latest version from nodejs v$NODE_MAJOR tree.";
 fi;
 echo "";
 echo "Your current setup is:";
@@ -152,10 +159,9 @@ if
                 NODENOTCORR=1
                 echo -e "$NOTCORRSTRG";
 else
-                echo -e "\n\n";
+                echo "";
 fi
-echo "";
-echo "I found these versions available for installation:";
+echo "I found these nodejs versions available for installation:";
 echo "";
         apt-cache policy nodejs;
 echo "";
@@ -164,12 +170,11 @@ echo "";
 if
         [[ "$NODENOTCORR" -eq 1 ]]
         then
-                echo -e "\n!!! THIS CODE IS IN BETA STAGE. TRY IT AT YOUR OWN RISK !!!";
-                echo -e "\n\nYour nodejs-Installation seems to be not correct. Shall we try to fix it?  \nDO NOT RUN FIX ON NON-LINUX-SYSTEMS!";
+                echo -e "\n\nYour nodejs-Installation seems to be not correct. Shall we try to fix it?";
                 echo "Press <y> to continue or any other key to quit";
                 read -r -s -n 1 charpaths;
         if
-                        [ "$charpaths" = "y" ]
+                        [[ "$charpaths" = "y" ]] || [[ "$charpaths" = "Y" ]]
                 then
                         echo -e "\nFixing your nodejs setup";
                 if
@@ -219,29 +224,31 @@ fi;
 if [[ "$VERNODE" = "v$NODERECOM" ]];
 then
 echo "Nothing to do, your installed version is the recommended one.";
+unset LC_ALL;
 exit;
 fi;
 if [[ "$VERNODE" != "v$NODERECOM" ]];
 then
-        echo -e "\n!!! THIS CODE IS IN BETA STAGE. TRY IT AT YOUR OWN RISK !!!";
-        echo -e "\nYou are running nodejs $VERNODE. Do you want to install recommended nodejs $NODERECOM? ";
+        echo -e "\nYou are running nodejs $VERNODE. Do you want to install recommended version $NODERECOM? ";
         echo -e "\nPress <y> to continue or any other key to quit";
         read -r -s -n 1 char;
         if
-                [ "$char" = "y" ]
+                [[ "$char" = "y" ]] || [[ "$char" = "Y" ]] 
         then
                 echo "Trying to fix your installation now. Please be patient."
-                $SUDOX rm "$($SUDOX find / -path /proc -prune -o -name nodesource.gpg -print)";
-                $SUDOX rm "$($SUDOX find / -path /proc -prune -o -name nodesource.key -print)";
+                # Finding nodesource.gpg or nodesource.key and deleting. Current key is pulled in later. 
+                $SUDOX rm "$($SUDOX find / \( -path /proc -o -path /dev -o -path /sys -o -path /lost+found \) -prune -o -name nodesource.[gk]* -print)";
+                # Deleting nodesource.list Will be recreated later.
                 $SUDOX rm /etc/apt/sources.list.d/nodesource.lis*;
         else 
         echo "I'm not fixing your installation. Exiting.";
-        exit 1;
+        exit;
         fi;
-                        if [ "$SYSTDDVIRT" != "none" ]; then
-                                echo "$SYSTDDVIRT";
-                                #sudo pkill -u iobroker;    #FIX ME! How to shut down iob in LXC without killing the script?
-                                                            #Using 'iob stop' in the meantime.
+
+        if [ "$SYSTDDVIRT" != "none" ]; then
+                echo "$SYSTDDVIRT";
+                        #sudo pkill -u iobroker;    #FIX ME! How to shut down iob in LXC without killing the script?
+                                                    #Using 'iob stop' in the meantime.
                                 iob stop;
                         else
                                 iob stop;
@@ -254,37 +261,52 @@ then
                         sleep 1                 # wait 1s between "frames"
                 done;
                 echo "";
+                        echo -e "\n*** These repos are active on your system:";
                         $SUDOX "$INSTALL_CMD" update;
-                        $SUDOX "$INSTALL_CMD" install ca-certificates curl gnupg;
+                        echo -e "\n*** Installing ca-certificates, curl and gnupg, just in case they are missing.";
+                        $SUDOX "$INSTALL_CMD" install -yqq ca-certificates curl gnupg;
+                        # Installing the key for  nodesource repository
                         $SUDOX mkdir -p /etc/apt/keyrings;
                         curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | $SUDOX gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg;
-                        echo -e "***\nCreating new /etc/apt/sources.list.d/nodesource.list file with this content:"
+                        # Setting up a fresh & clean nodesource.list 
+                        echo -e "\n*** Creating new /etc/apt/sources.list.d/nodesource.list and pinning source"
                         echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | $SUDOX tee /etc/apt/sources.list.d/nodesource.list;
-                        echo "***";
+                        echo "Package: nodejs" | $SUDOX tee -a /etc/apt/preferences.d/nodejs;
+                        echo "Pin: origin deb.nodesource.com" | $SUDOX tee -a /etc/apt/preferences.d/nodejs; 
+                        echo "Pin-Priority: 1001" | $SUDOX tee -a /etc/apt/preferences.d/nodejs;
+                        echo -e "\n*** These repos are active after the adjustments:"
                         $SUDOX "$INSTALL_CMD" update;
-                        if [[ $NODEINSTMAJOR -gt $NODE_MAJOR ]]
+                        
+                        echo "";
+                        echo "Installing the recommended nodejs version now!";
+                        if [ "$NODEINSTMAJOR" > "$NODE_MAJOR" ] 
                                 then
                                 $SUDOX "$INSTALL_CMD" install --reinstall --allow-downgrades -y nodejs="$NODERECOM"-1nodesource1 ;
                                 elif
-                                [[ "$NODERECOMNF" -eq 1 ]]
+                                [ "$NODERECOMNF" -eq 1 ]
                                 then
                                 #Falling back to initial release of nodejs recommended tree
                                 #NOT WORKING DUE TO TROUBLE WITH NODESOURCE REPO, TRY AGAIN LATER
                                 #NODERECOM=$NODE_MAJOR.0.0
                                 # Just another fallback for nodejs@18: 
                                 NODERECOM=18.17.0
+                                echo "Exact recommended version unknown, installing a fallback!";
                                 $SUDOX "$INSTALL_CMD" install --reinstall --allow-downgrades -y nodejs="$NODERECOM"-1nodesource1 ;
-                                $SUDOX "$INSTALL_CMD" update;
+                                echo -e "\nUpdating fallback to latest nodejs v$NODE_MAJOR release";
+                                $SUDOX "$INSTALL_CMD" update -qq;
                                 $SUDOX "$INSTALL_CMD" upgrade nodejs -y;
+                                VERNODE=$(node -v);
                                 fi;
                                 elif
-                                [[ $NODERECOM = "$VERNODE" ]] ; then 
+                                [ "$NODERECOMNF" -ne 1 ]; then 
                                 echo "Nothing to do, you are running the recommended version";
-                                echo "nodejs will now be updated using the usual 'apt update && apt full-upgrade' commands."
+                                echo "You can now keep your whole base system up-to-date using the usual 'sudo apt update && sudo apt full-upgrade' commands."
+                                echo "Please DO NOT USE node version managers like 'nvm', 'n' and others in parallel. They can crash your current installation"
                                 fi;
                                 #else;
-                                $SUDOX "$INSTALL_CMD" install --reinstall nodejs;
-                                #fi;
+                                if [ "$NODEINSTMAJOR" < "$NODE_MAJOR" ]
+                                then $SUDOX "$INSTALL_CMD" upgrade nodejs;
+                                fi;
                         #fi;
                 if [ "$SYSTDDVIRT" != "none" ]; then
                         echo -e "\n*** You need to manually restart your container now! *** ";
@@ -292,9 +314,9 @@ then
                         unset LC_ALL;
                         exit;
                 else
-                        iob restart;
-                        echo -e "\nWe tried our best to fix your nodejs. Please run 'iob diag' again to verify.";
+                        echo -e "\nWe tried our best to fix your nodejs. Please run iob diag again to verify.";
                         echo -e "\n*** RESTARTING ioBroker NOW! *** \n Please refresh or restart your browser in a few moments.";
+                        iob restart;   
                 fi;
         # else
                 echo "";
